export const CONTROLS = [
  {
    id: 'firewalls',
    title: 'Firewalls',
    subtitle: 'Control 1 of 5',
    icon: '🛡',
    ncsc: 'CE-FW',
    description: 'Firewalls act as your first line of defence — controlling exactly what traffic is permitted to enter and leave your network. Misconfigured or missing firewalls are the most common entry point for attackers.',
    threat: 'Unprotected networks are scanned and attacked within minutes of going online. A boundary firewall blocks the vast majority of automated attacks.',
    fields: [
      {
        key: 'firewall_on_all_devices',
        label: 'Firewalls are configured on all internet-connected devices',
        why: 'Every device without a firewall is a direct attack surface. This includes laptops used at home, remote workers, and any device on a guest network.',
        risk: 'critical',
        impact: 'Unprotected devices can be compromised remotely within minutes of connecting to the internet.',
        ce_ref: 'CE v3.3 §1.1',
      },
      {
        key: 'default_admin_password_changed',
        label: 'Default admin credentials have been changed on all firewalls and routers',
        why: 'Default passwords (admin/admin, admin/password) are publicly documented for every router model and are the first thing attackers try.',
        risk: 'critical',
        impact: 'An attacker with default credentials can disable your firewall entirely, redirecting all traffic through their systems.',
        ce_ref: 'CE v3.3 §1.3',
      },
      {
        key: 'unnecessary_ports_blocked',
        label: 'Unnecessary inbound network ports are blocked',
        why: 'Open ports are open doors. Ports not actively used for business should be closed by default — a principle known as default-deny.',
        risk: 'high',
        impact: 'Each open port is a potential entry point. Common exploits target ports 22 (SSH), 3389 (RDP), and 445 (SMB).',
        ce_ref: 'CE v3.3 §1.2',
      },
      {
        key: 'firewall_rules_documented',
        label: 'Firewall rules are documented and reviewed at least quarterly',
        why: 'Without documentation, firewall rules accumulate over years with no justification. Old rules create hidden vulnerabilities and make incident response impossible.',
        risk: 'medium',
        impact: 'Undocumented rules are unauditable. Assessors will ask to see your rule documentation — without it, you cannot demonstrate compliance.',
        ce_ref: 'CE v3.3 §1.4',
      },
      {
        key: 'boundary_firewall_in_place',
        label: 'A boundary firewall protects the entire network perimeter',
        why: 'A boundary firewall sits between your internal network and the internet, providing centralised protection for all devices regardless of their individual firewall settings.',
        risk: 'critical',
        impact: 'Without a boundary firewall, every internal device is directly exposed to internet-based attacks.',
        ce_ref: 'CE v3.3 §1.1',
      },
    ]
  },
  {
    id: 'secure_config',
    title: 'Secure Configuration',
    subtitle: 'Control 2 of 5',
    icon: '⚙',
    ncsc: 'CE-SC',
    description: 'Systems are insecure by default — they ship with features enabled, services running, and accounts active that you do not need. Secure configuration means systematically removing everything that is not required.',
    threat: 'Default configurations are the same across millions of identical devices. Attackers exploit this: they know exactly what\'s enabled by default and write automated tools to find it.',
    fields: [
      {
        key: 'default_passwords_changed',
        label: 'Default passwords have been changed on all systems, devices and software',
        why: 'Printers, servers, VoIP phones, backup appliances — all ship with default credentials. Many UK SME breaches start with a compromised printer or network device still using admin/admin.',
        risk: 'critical',
        impact: 'Default credentials give attackers immediate authenticated access to your systems without any hacking required.',
        ce_ref: 'CE v3.3 §2.1',
      },
      {
        key: 'unnecessary_software_removed',
        label: 'Unnecessary software, services and features are removed or disabled',
        why: 'Every piece of software installed is a potential attack surface. Bloatware, trial software, and legacy applications all represent unpatched, unmonitored risk.',
        risk: 'high',
        impact: 'Unused software still receives new vulnerabilities but is never patched. Attackers specifically target forgotten legacy applications.',
        ce_ref: 'CE v3.3 §2.2',
      },
      {
        key: 'auto_run_disabled',
        label: 'Auto-run and auto-play features are disabled across all systems',
        why: 'Auto-run automatically executes code from removable media (USB drives, CDs). This was the primary delivery mechanism for early ransomware and remains a risk.',
        risk: 'medium',
        impact: 'A malicious USB drive plugged into any device could execute malware automatically without any user action.',
        ce_ref: 'CE v3.3 §2.3',
      },
      {
        key: 'configuration_process_exists',
        label: 'A documented process exists for managing and auditing system configurations',
        why: 'Without a baseline configuration, you cannot detect when systems drift from their secure state. Configuration management is how you maintain security over time, not just at setup.',
        risk: 'high',
        impact: 'Configuration drift means systems gradually become less secure over time. Without a baseline, you cannot detect or remediate this.',
        ce_ref: 'CE v3.3 §2.4',
      },
      {
        key: 'software_inventory_maintained',
        label: 'An up-to-date inventory of all software is maintained',
        why: 'You cannot patch software you do not know exists. A software inventory is the foundation of patch management and is required evidence for assessors.',
        risk: 'high',
        impact: 'Shadow IT — software installed without IT knowledge — is frequently unpatched and a primary attack vector.',
        ce_ref: 'CE v3.3 §2.5',
      },
    ]
  },
  {
    id: 'access_control',
    title: 'Access Control',
    subtitle: 'Control 3 of 5',
    icon: '🔑',
    ncsc: 'CE-AC',
    description: 'Access control ensures that only authorised people can access your systems and data, and only to the extent they need for their role. It is the primary defence against both external attackers and insider threats.',
    threat: 'Credential theft is now the most common initial attack vector. Once an attacker has valid credentials, they can move through your systems undetected — often for months.',
    fields: [
      {
        key: 'unique_accounts_per_user',
        label: 'Every individual has their own unique, named user account — no shared logins',
        why: 'Shared accounts make it impossible to track who did what, hold individuals accountable, or revoke access for a specific person without affecting everyone.',
        risk: 'high',
        impact: 'Shared accounts are a GDPR compliance risk and make incident investigation impossible — you cannot prove which individual accessed data.',
        ce_ref: 'CE v3.3 §3.1',
      },
      {
        key: 'admin_access_restricted',
        label: 'Administrative privileges are limited strictly to those whose role requires them',
        why: 'Admin accounts are the highest-value target for attackers. Staff using admin accounts for daily work (email, browsing) massively increases the blast radius of any phishing attack.',
        risk: 'critical',
        impact: 'A phishing email clicked on an admin account gives the attacker full system access immediately. The same email on a standard account is limited in damage.',
        ce_ref: 'CE v3.3 §3.2',
      },
      {
        key: 'mfa_for_remote_access',
        label: 'Multi-factor authentication (MFA) is enforced for all remote access and cloud services',
        why: 'From April 2026, MFA is an AUTOMATIC FAIL if not implemented on any cloud service where it is available. This is the single most common reason for Cyber Essentials failures.',
        risk: 'critical',
        impact: 'Without MFA, a stolen password gives an attacker full remote access. MFA blocks 99.9% of automated credential attacks.',
        ce_ref: 'CE v3.3 §3.3 — AUTO-FAIL from April 2026',
        urgent: true,
      },
      {
        key: 'offboarding_process_exists',
        label: 'Access is revoked on the same day a staff member or contractor leaves',
        why: 'Ex-employees retaining access is one of the most common insider threat scenarios. A disgruntled former employee with active credentials is a serious liability.',
        risk: 'critical',
        impact: 'Former staff accessing client data after leaving is a notifiable GDPR breach. You are legally required to report it to the ICO within 72 hours.',
        ce_ref: 'CE v3.3 §3.4',
      },
      {
        key: 'privileged_account_monitoring',
        label: 'Privileged and admin accounts are actively monitored for unusual activity',
        why: 'When attackers compromise an admin account, they operate slowly and carefully to avoid detection. Without monitoring, the average dwell time is 200+ days before discovery.',
        risk: 'high',
        impact: 'Unmonitored admin accounts allow attackers to operate inside your network for months, exfiltrating data gradually.',
        ce_ref: 'CE v3.3 §3.5',
      },
    ]
  },
  {
    id: 'malware_protection',
    title: 'Malware Protection',
    subtitle: 'Control 4 of 5',
    icon: '🦠',
    ncsc: 'CE-MP',
    description: 'Malware — ransomware, spyware, trojans — is the primary tool used in the majority of successful cyberattacks against UK SMEs. Protection requires multiple overlapping layers, not just antivirus software.',
    threat: 'Ransomware attacks on UK SMEs increased 100% in 2025. The average ransom demand for an SME is £47,000 — not including the cost of downtime, recovery, and reputational damage.',
    fields: [
      {
        key: 'antivirus_installed',
        label: 'Anti-malware software is installed and active on all in-scope devices',
        why: 'Every device — including those used by remote workers and contractors — must have active malware protection. Windows Defender is acceptable if properly configured.',
        risk: 'critical',
        impact: 'Unprotected devices can be infected within seconds of visiting a compromised website or opening a malicious attachment.',
        ce_ref: 'CE v3.3 §4.1',
      },
      {
        key: 'antivirus_auto_updates',
        label: 'Anti-malware definitions update automatically — at least daily',
        why: 'New malware variants are released hourly. An antivirus database that is even a few days out of date may not recognise the latest ransomware variants.',
        risk: 'high',
        impact: 'A 1-week-old signature database will miss thousands of new malware variants. Auto-updates are non-negotiable.',
        ce_ref: 'CE v3.3 §4.1',
      },
      {
        key: 'web_filtering_in_place',
        label: 'Web filtering blocks access to known malicious, phishing and high-risk websites',
        why: 'Drive-by downloads can infect a device simply by visiting a compromised website — no clicks required. Web filtering blocks known malicious domains before the browser loads them.',
        risk: 'high',
        impact: 'Without web filtering, a single click on a phishing link can result in ransomware deployment across your entire network within hours.',
        ce_ref: 'CE v3.3 §4.2',
      },
      {
        key: 'email_scanning_active',
        label: 'All inbound and outbound email is scanned for malware and phishing',
        why: 'Email is the primary delivery vector for malware — 91% of all cyberattacks begin with a phishing email. Microsoft 365 Defender and Google Workspace both offer this natively.',
        risk: 'critical',
        impact: 'Business email compromise (BEC) cost UK businesses over £1.2 billion in 2024. Email scanning catches the vast majority of these attacks before they reach inboxes.',
        ce_ref: 'CE v3.3 §4.3',
      },
      {
        key: 'usb_usage_controlled',
        label: 'Removable media (USB drives, external hard drives) usage is controlled or restricted',
        why: 'USB drives are a dual threat — they can introduce malware and be used to exfiltrate confidential data. Many high-profile breaches began with a found or gifted USB drive.',
        risk: 'medium',
        impact: 'An unencrypted USB containing client data lost on a train is a notifiable GDPR breach. USB restrictions prevent both infection and data loss.',
        ce_ref: 'CE v3.3 §4.4',
      },
    ]
  },
  {
    id: 'patch_management',
    title: 'Patch Management',
    subtitle: 'Control 5 of 5',
    icon: '🔧',
    ncsc: 'CE-PM',
    description: 'Software vulnerabilities are discovered daily. Patches fix these vulnerabilities — but only if they are applied quickly. Unpatched systems are the most exploited attack vector in the UK, accounting for the majority of ransomware incidents.',
    threat: 'The average time between a vulnerability being disclosed and it being actively exploited is now less than 5 days. The Cyber Essentials 14-day rule exists precisely because attackers move this fast.',
    fields: [
      {
        key: 'auto_updates_enabled',
        label: 'Automatic updates are enabled for all operating systems and software',
        why: 'Manual patching is unreliable — it depends on someone remembering to do it. Automatic updates ensure critical patches are applied as soon as they are released.',
        risk: 'high',
        impact: 'Manual patch processes typically result in 30–90 day lag between patch release and deployment, leaving systems vulnerable for weeks.',
        ce_ref: 'CE v3.3 §5.1',
      },
      {
        key: 'patches_applied_within_14_days',
        label: 'Critical and high-severity security patches are applied within 14 days of release',
        why: 'From April 2026, failing to apply critical patches within 14 days is an AUTOMATIC FAIL for Cyber Essentials. This applies to ALL in-scope devices — including those of remote workers.',
        risk: 'critical',
        impact: 'The WannaCry ransomware attack exploited a vulnerability for which Microsoft had released a patch 60 days earlier. Timely patching would have prevented it.',
        ce_ref: 'CE v3.3 §5.2 — AUTO-FAIL from April 2026',
        urgent: true,
      },
      {
        key: 'unsupported_software_removed',
        label: 'All software and operating systems are currently supported and receiving security updates',
        why: 'Windows 10 reached end-of-life in October 2025. Any device still running Windows 10 will automatically fail Cyber Essentials from that date.',
        risk: 'critical',
        impact: 'End-of-life software will never receive security patches for newly discovered vulnerabilities, making it permanently insecure.',
        ce_ref: 'CE v3.3 §5.3',
      },
      {
        key: 'asset_inventory_exists',
        label: 'A complete hardware and software asset inventory is maintained and kept current',
        why: 'You cannot patch what you do not know exists. An asset inventory is the foundation of patch management and is required evidence for Cyber Essentials assessors.',
        risk: 'high',
        impact: 'Shadow IT — devices connected to your network without IT knowledge — are never patched. They become the easiest entry point for attackers.',
        ce_ref: 'CE v3.3 §5.4',
      },
      {
        key: 'patch_process_documented',
        label: 'A documented patch management process exists, with named roles and responsibilities',
        why: 'Without documentation, patching is ad-hoc and unauditable. Assessors will ask to see your patch management process — a verbal description is not sufficient.',
        risk: 'medium',
        impact: 'Undocumented processes fail when key staff leave or are absent. A documented process ensures patching continues regardless of personnel changes.',
        ce_ref: 'CE v3.3 §5.5',
      },
    ]
  }
]

export const COMPANY_SIZES = [
  '1-9 employees',
  '10-49 employees',
  '50-249 employees',
  '250+ employees',
]

export const initialAnswers = () => ({
  firewalls: {
    firewall_on_all_devices: null,
    default_admin_password_changed: null,
    unnecessary_ports_blocked: null,
    firewall_rules_documented: null,
    boundary_firewall_in_place: null,
  },
  secure_config: {
    default_passwords_changed: null,
    unnecessary_software_removed: null,
    auto_run_disabled: null,
    configuration_process_exists: null,
    software_inventory_maintained: null,
  },
  access_control: {
    unique_accounts_per_user: null,
    admin_access_restricted: null,
    mfa_for_remote_access: null,
    offboarding_process_exists: null,
    privileged_account_monitoring: null,
  },
  malware_protection: {
    antivirus_installed: null,
    antivirus_auto_updates: null,
    web_filtering_in_place: null,
    email_scanning_active: null,
    usb_usage_controlled: null,
  },
  patch_management: {
    auto_updates_enabled: null,
    patches_applied_within_14_days: null,
    unsupported_software_removed: null,
    asset_inventory_exists: null,
    patch_process_documented: null,
  }
})
