export const CONTROLS = [
  {
    id: 'firewalls',
    title: 'Firewalls',
    subtitle: 'Control 1 of 5',
    icon: '🛡',
    ncsc: 'CE-FW',
    description: 'Firewalls act as your first line of defence — controlling exactly what traffic is permitted to enter and leave your network.',
    threat: 'Unprotected networks are scanned and attacked within minutes of going online. A boundary firewall blocks the vast majority of automated attacks.',
    fields: [
      {
        key: 'firewall_on_all_devices',
        label: 'Firewalls are configured on all internet-connected devices',
        why: 'Every device without a firewall is a direct attack surface. This includes laptops used at home, remote workers, and any device on a guest network.',
        risk: 'critical',
        impact: 'Unprotected devices can be compromised remotely within minutes of connecting to the internet.',
        ce_ref: 'CE v3.3 §1.1',
      },
      {
        key: 'default_admin_password_changed',
        label: 'Default admin credentials have been changed on all firewalls and routers',
        why: 'Default passwords (admin/admin, admin/password) are publicly documented for every router model and are the first thing attackers try.',
        risk: 'critical',
        impact: 'An attacker with default credentials can disable your firewall entirely.',
        ce_ref: 'CE v3.3 §1.3',
      },
      {
        key: 'unnecessary_ports_blocked',
        label: 'Unnecessary inbound network ports are blocked',
        why: 'Open ports are open doors. Ports not actively used for business should be closed by default.',
        risk: 'high',
        impact: 'Each open port is a potential entry point for attackers.',
        ce_ref: 'CE v3.3 §1.2',
      },
      {
        key: 'firewall_rules_documented',
        label: 'Firewall rules are documented and reviewed at least quarterly',
        why: 'Without documentation, firewall rules accumulate over years with no justification. Assessors will ask to see documentation.',
        risk: 'medium',
        impact: 'Undocumented rules are unauditable and create hidden vulnerabilities.',
        ce_ref: 'CE v3.3 §1.4',
      },
      {
        key: 'boundary_firewall_in_place',
        label: 'A boundary firewall protects the entire network perimeter',
        why: 'A boundary firewall sits between your internal network and the internet, providing centralised protection.',
        risk: 'critical',
        impact: 'Without a boundary firewall, every internal device is directly exposed to internet-based attacks.',
        ce_ref: 'CE v3.3 §1.1',
      },
      {
        key: 'software_firewall_on_devices',
        label: 'Software firewalls are enabled on all laptops and desktops (especially for remote workers)',
        why: 'CE v3.3 requires software firewalls on all devices used outside the office. Remote workers cannot rely on the office boundary firewall.',
        risk: 'high',
        impact: 'Laptops used at home or in cafes without a software firewall are directly exposed to the internet.',
        ce_ref: 'CE v3.3 §1.4',
      },
      {
        key: 'cloud_firewall_configured',
        label: 'If using cloud hosting (AWS/Azure/GCP), security groups are configured to restrict access',
        why: 'Cloud services cannot be excluded from CE scope in v3.3. Any cloud-hosted service must have equivalent firewall controls.',
        risk: 'high',
        impact: 'Misconfigured cloud security groups are the most common cause of cloud data breaches.',
        ce_ref: 'CE v3.3 §1.5 Cloud',
      },
    ]
  },
  {
    id: 'secure_config',
    title: 'Secure Configuration',
    subtitle: 'Control 2 of 5',
    icon: '⚙',
    ncsc: 'CE-SC',
    description: 'Systems are insecure by default — they ship with features enabled and accounts active that you do not need. Secure configuration means removing everything that is not required.',
    threat: 'Default configurations are the same across millions of devices. Attackers exploit this — they know exactly what is enabled by default.',
    fields: [
      {
        key: 'default_passwords_changed',
        label: 'Default passwords have been changed on all systems, devices and software',
        why: 'Printers, servers, VoIP phones, backup appliances — all ship with default credentials that are publicly known.',
        risk: 'critical',
        impact: 'Default credentials give attackers immediate authenticated access without any hacking.',
        ce_ref: 'CE v3.3 §2.1',
      },
      {
        key: 'unnecessary_software_removed',
        label: 'Unnecessary software, services and features are removed or disabled',
        why: 'Every piece of software installed is a potential attack surface. Bloatware and legacy applications are unpatched risks.',
        risk: 'high',
        impact: 'Unused software still receives new vulnerabilities but is never patched.',
        ce_ref: 'CE v3.3 §2.2',
      },
      {
        key: 'auto_run_disabled',
        label: 'Auto-run and auto-play features are disabled across all systems',
        why: 'Auto-run automatically executes code from removable media. This is a primary malware delivery mechanism.',
        risk: 'medium',
        impact: 'A malicious USB drive could execute malware automatically without any user action.',
        ce_ref: 'CE v3.3 §2.3',
      },
      {
        key: 'configuration_process_exists',
        label: 'A documented process exists for managing and auditing system configurations',
        why: 'Without a baseline, systems drift from their secure state. Configuration management is how you maintain security over time.',
        risk: 'high',
        impact: 'Configuration drift means systems gradually become less secure without anyone noticing.',
        ce_ref: 'CE v3.3 §2.4',
      },
      {
        key: 'software_inventory_maintained',
        label: 'An up-to-date inventory of all software is maintained',
        why: 'You cannot patch software you do not know exists. A software inventory is required evidence for CE assessors.',
        risk: 'high',
        impact: 'Shadow IT — software installed without IT knowledge — is frequently unpatched.',
        ce_ref: 'CE v3.3 §2.5',
      },
      {
        key: 'screen_lock_enabled',
        label: 'All devices automatically lock after a period of inactivity (maximum 15 minutes)',
        why: 'An unlocked device left unattended allows anyone to access its contents. CE v3.3 requires auto-lock on all in-scope devices.',
        risk: 'medium',
        impact: 'Unlocked devices in public places or open offices are a significant data breach risk.',
        ce_ref: 'CE v3.3 §2.6',
      },
      {
        key: 'cloud_security_defaults',
        label: 'Cloud service security defaults are reviewed and enabled (M365 Security Defaults, Google Workspace security settings)',
        why: 'Microsoft and Google provide free security baseline configurations. Many SMEs never enable them, leaving accounts vulnerable.',
        risk: 'high',
        impact: 'Default cloud configurations often leave accounts exposed to credential attacks and data leakage.',
        ce_ref: 'CE v3.3 §2.7 Cloud',
      },
    ]
  },
  {
    id: 'access_control',
    title: 'User Access Control',
    subtitle: 'Control 3 of 5',
    icon: '🔑',
    ncsc: 'CE-AC',
    description: 'Access control ensures that only authorised people can access your systems and data, and only to the extent they need for their role.',
    threat: 'Credential theft is the most common initial attack vector. Once an attacker has valid credentials, they can move through your systems undetected for months.',
    fields: [
      {
        key: 'unique_accounts_per_user',
        label: 'Every individual has their own unique, named user account — no shared logins',
        why: 'Shared accounts make it impossible to track who did what, hold individuals accountable, or revoke one person\'s access.',
        risk: 'high',
        impact: 'Shared accounts are a GDPR compliance risk and make incident investigation impossible.',
        ce_ref: 'CE v3.3 §3.1',
      },
      {
        key: 'admin_access_restricted',
        label: 'Administrative privileges are limited strictly to those whose role requires them',
        why: 'Admin accounts are the highest-value target. Staff using admin accounts for daily email/browsing massively increases risk.',
        risk: 'critical',
        impact: 'A phishing email clicked on an admin account gives the attacker full system access immediately.',
        ce_ref: 'CE v3.3 §3.2',
      },
      {
        key: 'mfa_for_remote_access',
        label: 'MFA is enforced for all remote access (VPN, RDP, remote desktop)',
        why: 'MFA on remote access is mandatory under CE v3.3. Without it, a stolen password gives full remote access.',
        risk: 'critical',
        impact: 'MFA blocks 99.9% of automated credential attacks. Without it, remote access is highly vulnerable.',
        ce_ref: 'CE v3.3 §3.3',
        urgent: true,
      },
      {
        key: 'mfa_on_cloud_services',
        label: 'MFA is enabled on Microsoft 365 / Google Workspace for ALL users',
        why: 'CE v3.3 (April 2026): MFA on cloud services is now an AUTOMATIC FAIL if not implemented. This is the most common reason for CE failures.',
        risk: 'critical',
        impact: 'Without MFA, a single compromised password gives an attacker full access to your email, files and collaboration tools.',
        ce_ref: 'CE v3.3 §3.4 — AUTO-FAIL',
        urgent: true,
      },
      {
        key: 'offboarding_process_exists',
        label: 'Access is revoked on the same day a staff member or contractor leaves',
        why: 'Ex-employees retaining access is one of the most common insider threat scenarios and a notifiable GDPR breach risk.',
        risk: 'critical',
        impact: 'Former staff accessing client data after leaving is a notifiable GDPR breach requiring ICO notification within 72 hours.',
        ce_ref: 'CE v3.3 §3.5',
      },
      {
        key: 'separate_admin_accounts',
        label: 'IT administrators use a separate, dedicated admin account only for administrative tasks',
        why: 'Using an admin account for daily work (email, browsing) exposes it to phishing and drive-by attacks.',
        risk: 'high',
        impact: 'An admin account compromised via phishing gives attackers domain-level access to your entire network.',
        ce_ref: 'CE v3.3 §3.2',
      },
      {
        key: 'third_party_accounts_reviewed',
        label: 'Third-party supplier and contractor accounts are reviewed and removed when no longer needed',
        why: 'CE v3.3 now explicitly requires third-party account lifecycle management. Forgotten supplier accounts are a hidden access risk.',
        risk: 'high',
        impact: 'A former supplier with active system access could access client data or systems without detection.',
        ce_ref: 'CE v3.3 §3.6',
      },
    ]
  },
  {
    id: 'malware_protection',
    title: 'Malware Protection',
    subtitle: 'Control 4 of 5',
    icon: '🦠',
    ncsc: 'CE-MP',
    description: 'Malware — ransomware, spyware, trojans — is the primary tool in the majority of successful cyberattacks against UK SMEs.',
    threat: 'Ransomware attacks on UK SMEs increased 100% in 2025. The average ransom demand for an SME is £47,000 — not including the cost of downtime and recovery.',
    fields: [
      {
        key: 'antivirus_installed',
        label: 'Anti-malware software is installed and active on all in-scope devices',
        why: 'Every device — including those used by remote workers — must have active malware protection. Windows Defender is acceptable if properly configured.',
        risk: 'critical',
        impact: 'Unprotected devices can be infected within seconds of visiting a compromised website.',
        ce_ref: 'CE v3.3 §4.1',
      },
      {
        key: 'antivirus_auto_updates',
        label: 'Anti-malware definitions update automatically — at least daily',
        why: 'New malware variants are released hourly. An out-of-date database will not recognise the latest ransomware variants.',
        risk: 'high',
        impact: 'A week-old signature database will miss thousands of new malware variants.',
        ce_ref: 'CE v3.3 §4.1',
      },
      {
        key: 'web_filtering_in_place',
        label: 'Web filtering blocks access to known malicious and phishing websites',
        why: 'Drive-by downloads can infect a device simply by visiting a compromised website — no clicks required.',
        risk: 'high',
        impact: 'Without web filtering, a single click on a phishing link can result in ransomware across your network.',
        ce_ref: 'CE v3.3 §4.2',
      },
      {
        key: 'email_scanning_active',
        label: 'All inbound and outbound email is scanned for malware and phishing',
        why: 'Email is the primary delivery vector for malware — 91% of cyberattacks begin with a phishing email.',
        risk: 'critical',
        impact: 'Business email compromise cost UK businesses over £1.2 billion in 2024.',
        ce_ref: 'CE v3.3 §4.3',
      },
      {
        key: 'usb_usage_controlled',
        label: 'Removable media (USB drives, external hard drives) usage is controlled or restricted',
        why: 'USB drives can introduce malware and exfiltrate data. An unencrypted USB with client data lost on a train is a notifiable GDPR breach.',
        risk: 'medium',
        impact: 'USB restrictions prevent both infection and accidental data loss.',
        ce_ref: 'CE v3.3 §4.4',
      },
      {
        key: 'av_centrally_managed',
        label: 'Antivirus is centrally managed — users cannot disable or override it',
        why: 'CE v3.3 requires that malware protection cannot be disabled by users. User-managed AV is frequently turned off "temporarily" and never re-enabled.',
        risk: 'high',
        impact: 'User-controlled AV is routinely disabled, leaving devices unprotected for extended periods.',
        ce_ref: 'CE v3.3 §4.1',
      },
      {
        key: 'mobile_devices_protected',
        label: 'Mobile phones and tablets are protected by antivirus or a Mobile Device Management (MDM) solution',
        why: 'CE v3.3 brings mobile devices explicitly into scope. Phones accessing company email or data must have equivalent protection.',
        risk: 'high',
        impact: 'Unprotected mobile devices are increasingly targeted by sophisticated mobile malware.',
        ce_ref: 'CE v3.3 §4.5',
      },
    ]
  },
  {
    id: 'patch_management',
    title: 'Security Update Management',
    subtitle: 'Control 5 of 5',
    icon: '🔧',
    ncsc: 'CE-PM',
    description: 'Software vulnerabilities are discovered daily. Patches fix these vulnerabilities — but only if applied quickly. Unpatched systems are the most exploited attack vector in the UK.',
    threat: 'The average time between a vulnerability being disclosed and actively exploited is now less than 5 days. The CE 14-day rule exists because attackers move this fast.',
    fields: [
      {
        key: 'auto_updates_enabled',
        label: 'Automatic updates are enabled for all operating systems and software',
        why: 'Manual patching is unreliable — it depends on someone remembering. Auto-updates ensure critical patches are applied immediately.',
        risk: 'high',
        impact: 'Manual patch processes typically result in 30-90 day lag between release and deployment.',
        ce_ref: 'CE v3.3 §5.1',
      },
      {
        key: 'patches_applied_within_14_days',
        label: 'Critical and high-severity security patches are applied within 14 days of release',
        why: 'CE v3.3 (April 2026): Failing to patch within 14 days is an AUTOMATIC FAIL. This applies to ALL in-scope devices including remote workers.',
        risk: 'critical',
        impact: 'The WannaCry ransomware attack exploited a vulnerability for which a patch had been available for 60 days.',
        ce_ref: 'CE v3.3 §5.2 — AUTO-FAIL',
        urgent: true,
      },
      {
        key: 'unsupported_software_removed',
        label: 'All software and operating systems are currently supported and receiving security updates',
        why: 'Windows 10 reached end-of-life in October 2025. Any unsupported OS is an automatic CE fail.',
        risk: 'critical',
        impact: 'End-of-life software never receives patches for newly discovered vulnerabilities — permanently insecure.',
        ce_ref: 'CE v3.3 §5.3',
      },
      {
        key: 'asset_inventory_exists',
        label: 'A complete hardware and software asset inventory is maintained and kept current',
        why: 'You cannot patch what you do not know exists. A full asset inventory is required evidence for CE assessors.',
        risk: 'high',
        impact: 'Shadow IT — devices connected without IT knowledge — are never patched and are the easiest entry point.',
        ce_ref: 'CE v3.3 §5.4',
      },
      {
        key: 'patch_process_documented',
        label: 'A documented patch management process exists, with named roles and responsibilities',
        why: 'Without documentation, patching is ad-hoc and unauditable. Assessors require written evidence of your patch process.',
        risk: 'medium',
        impact: 'Undocumented processes fail when key staff leave. Documentation ensures continuity.',
        ce_ref: 'CE v3.3 §5.5',
      },
      {
        key: 'firmware_updated',
        label: 'Router and firewall firmware is updated regularly',
        why: 'CE v3.3 explicitly includes network device firmware. Routers are frequently forgotten in patch cycles despite being critical infrastructure.',
        risk: 'high',
        impact: 'Unpatched router firmware is a common attack vector — attackers can intercept all network traffic.',
        ce_ref: 'CE v3.3 §5.6',
      },
      {
        key: 'mobile_devices_patched',
        label: 'Mobile phones and tablets are kept up to date with the latest OS and app updates',
        why: 'Mobile devices are now in scope for CE v3.3. An unpatched phone accessing company email is an in-scope security gap.',
        risk: 'high',
        impact: 'Mobile OS vulnerabilities are increasingly targeted by sophisticated attackers.',
        ce_ref: 'CE v3.3 §5.7',
      },
    ]
  }
]

export const COMPANY_SIZES = [
  '1-9 employees',
  '10-49 employees',
  '50-249 employees',
  '250+ employees',
]

export const CLOUD_SERVICES_OPTIONS = [
  'Microsoft 365',
  'Google Workspace',
  'AWS',
  'Azure',
  'Google Cloud',
  'Xero / QuickBooks',
  'Salesforce / CRM',
  'Dropbox / OneDrive / Google Drive',
  'Slack / Teams',
  'Other SaaS tools',
  'None',
]

export const INDUSTRIES = [
  'Professional Services (Legal / Accountancy)',
  'Healthcare / NHS Supply Chain',
  'Financial Services',
  'Retail / E-commerce',
  'Technology / Software',
  'Construction / Trades',
  'Education',
  'Charity / Non-profit',
  'Manufacturing',
  'Other',
]

export const initialAnswers = () => ({
  firewalls: {
    firewall_on_all_devices:        null,
    default_admin_password_changed: null,
    unnecessary_ports_blocked:      null,
    firewall_rules_documented:      null,
    boundary_firewall_in_place:     null,
    software_firewall_on_devices:   null,
    cloud_firewall_configured:      null,
  },
  secure_config: {
    default_passwords_changed:      null,
    unnecessary_software_removed:   null,
    auto_run_disabled:              null,
    configuration_process_exists:   null,
    software_inventory_maintained:  null,
    screen_lock_enabled:            null,
    cloud_security_defaults:        null,
  },
  access_control: {
    unique_accounts_per_user:       null,
    admin_access_restricted:        null,
    mfa_for_remote_access:          null,
    mfa_on_cloud_services:          null,
    offboarding_process_exists:     null,
    separate_admin_accounts:        null,
    third_party_accounts_reviewed:  null,
    privileged_account_monitoring:  null,
  },
  malware_protection: {
    antivirus_installed:            null,
    antivirus_auto_updates:         null,
    web_filtering_in_place:         null,
    email_scanning_active:          null,
    usb_usage_controlled:           null,
    av_centrally_managed:           null,
    mobile_devices_protected:       null,
  },
  patch_management: {
    auto_updates_enabled:           null,
    patches_applied_within_14_days: null,
    unsupported_software_removed:   null,
    asset_inventory_exists:         null,
    patch_process_documented:       null,
    firmware_updated:               null,
    mobile_devices_patched:         null,
  }
})
